import { HazardZone, SOSCluster, SOSEvent } from "./types";

export const HIMALAYAN_ZONES: HazardZone[] = [
  {
    id: "chamoli_01",
    name: "Chamoli (Rishi Ganga - Dhauliganga Valley)",
    district: "Chamoli",
    center: [30.5573, 79.5642],
    currentRisk: 86.4,
    alertColor: "RED",
    primaryTrigger: "Cryo-Seismic GLOF Signature (4.6M Tremor + Moraine Lake Breached)",
    leadTimeMinutes: 225, // 3h 45m
    dangerMarkM: 7.5,
    warningMarkM: 6.0,
    telemetry: {
      rainfall_mm: 18.5,
      soil_moisture_pct: 82.0,
      slope_deg: 44.5,
      river_level_m: 6.8,
      seismic_mag: 4.6,
    },
    hydrograph: [
      { time: "-06h", level_m: 3.2, discharge_cumecs: 180, isPredicted: false },
      { time: "-04h", level_m: 3.6, discharge_cumecs: 240, isPredicted: false },
      { time: "-02h", level_m: 4.8, discharge_cumecs: 460, isPredicted: false },
      { time: "NOW",  level_m: 6.8, discharge_cumecs: 890, isPredicted: false },
      { time: "+02h", level_m: 7.9, discharge_cumecs: 1420, isPredicted: true },
      { time: "+04h", level_m: 8.6, discharge_cumecs: 1850, isPredicted: true },
      { time: "+06h", level_m: 7.2, discharge_cumecs: 1100, isPredicted: true },
      { time: "+08h", level_m: 5.4, discharge_cumecs: 680, isPredicted: true },
    ],
    preventiveDirectives: [
      {
        id: "dir-101",
        category: "DAM",
        title: "Tapovan-Vishnugad Barrage Sluice Pre-Release",
        action: "Open Spillway Gates 1, 2, and 4 by 45% to lower reservoir baseline by 3.5m ahead of incoming 1,850 m³/s surge.",
        priority: "IMMEDIATE",
        deadline: "T - 90 mins",
        executed: false,
      },
      {
        id: "dir-102",
        category: "HIGHWAY",
        title: "NH-7 (Badrinath Highway) Traffic Halt",
        action: "Order Uttarakhand Police & BRO to halt civilian traffic at Helang and Joshimath checkpoints. Close low-lying river bridges.",
        priority: "IMMEDIATE",
        deadline: "T - 45 mins",
        executed: false,
      },
      {
        id: "dir-103",
        category: "PILGRIMAGE",
        title: "Govindghat Riverside Pilgrimage Camp Clearing",
        action: "Order SDMA SDRF personnel to evacuate 400+ pilgrims from temporary riverbank shelters to high-ground Gurdwara grounds.",
        priority: "IMMEDIATE",
        deadline: "T - 60 mins",
        executed: false,
      },
      {
        id: "dir-104",
        category: "POWER",
        title: "NTPC Hydroelectric Intake Tunnel Shutdown",
        action: "Depressurize power intake tunnels to avoid silt sedimentation and structural collapse.",
        priority: "ADVISORY",
        deadline: "T - 120 mins",
        executed: true,
      },
    ],
    infrastructure: [
      {
        id: "infra-1",
        name: "Tapovan Vishnugad Barrage",
        type: "BARRAGE",
        coords: [30.5489, 79.5785],
        riskLevel: "HIGH",
        bufferDistanceM: 30,
      },
      {
        id: "infra-2",
        name: "Rishi Ganga Hydel Intake Bridge",
        type: "BRIDGE",
        coords: [30.5542, 79.5698],
        riskLevel: "HIGH",
        bufferDistanceM: 15,
      },
      {
        id: "infra-3",
        name: "Joshimath Helipad Base (High Ground)",
        type: "SHELTER",
        coords: [30.5621, 79.5523],
        riskLevel: "SAFE",
        bufferDistanceM: 450,
      },
    ],
  },
  {
    id: "kedarnath_01",
    name: "Kedarnath Valley (Mandakini Catchment)",
    district: "Rudraprayag",
    center: [30.7346, 79.0669],
    currentRisk: 64.2,
    alertColor: "ORANGE",
    primaryTrigger: "High Saturated Runoff & Localized Cloudburst Warning",
    leadTimeMinutes: 85,
    dangerMarkM: 6.8,
    warningMarkM: 5.5,
    telemetry: {
      rainfall_mm: 68.2,
      soil_moisture_pct: 91.5,
      slope_deg: 38.0,
      river_level_m: 4.9,
      seismic_mag: 1.2,
    },
    hydrograph: [
      { time: "-06h", level_m: 2.8, discharge_cumecs: 120, isPredicted: false },
      { time: "-04h", level_m: 3.2, discharge_cumecs: 160, isPredicted: false },
      { time: "-02h", level_m: 4.1, discharge_cumecs: 290, isPredicted: false },
      { time: "NOW",  level_m: 4.9, discharge_cumecs: 480, isPredicted: false },
      { time: "+02h", level_m: 6.9, discharge_cumecs: 980, isPredicted: true },
      { time: "+04h", level_m: 7.4, discharge_cumecs: 1120, isPredicted: true },
      { time: "+06h", level_m: 5.8, discharge_cumecs: 620, isPredicted: true },
      { time: "+08h", level_m: 4.2, discharge_cumecs: 340, isPredicted: true },
    ],
    preventiveDirectives: [
      {
        id: "dir-201",
        category: "PILGRIMAGE",
        title: "Gaurikund-Kedarnath Trek Trail Suspension",
        action: "Halt uphill pilgrim movement at Gaurikund base. Direct downhill walkers to designated concrete shelters.",
        priority: "IMMEDIATE",
        deadline: "T - 30 mins",
        executed: false,
      },
      {
        id: "dir-202",
        category: "DAM",
        title: "Singoli-Bhatwari Hydroelectric Gate Flush",
        action: "Initiate radial gate opening to flush sediment and prevent reservoir backwater surge.",
        priority: "ADVISORY",
        deadline: "T - 75 mins",
        executed: false,
      },
    ],
    infrastructure: [
      {
        id: "infra-4",
        name: "Rambara Suspension Footbridge",
        type: "BRIDGE",
        coords: [30.7012, 79.0534],
        riskLevel: "HIGH",
        bufferDistanceM: 20,
      },
      {
        id: "infra-5",
        name: "Gaurikund Evacuation Muster Station",
        type: "SHELTER",
        coords: [30.6521, 79.0278],
        riskLevel: "SAFE",
        bufferDistanceM: 220,
      },
    ],
  },
  {
    id: "joshimath_01",
    name: "Joshimath Subsidence & Alaknanda Buffer",
    district: "Chamoli",
    center: [30.5562, 79.5663],
    currentRisk: 78.9,
    alertColor: "RED",
    primaryTrigger: "Geotechnical Slope Saturation & Toe-Erosion Breach Risk",
    leadTimeMinutes: 170,
    dangerMarkM: 7.2,
    warningMarkM: 5.8,
    telemetry: {
      rainfall_mm: 34.0,
      soil_moisture_pct: 87.2,
      slope_deg: 41.2,
      river_level_m: 5.4,
      seismic_mag: 3.1,
    },
    hydrograph: [
      { time: "-06h", level_m: 3.0, discharge_cumecs: 190, isPredicted: false },
      { time: "-04h", level_m: 3.8, discharge_cumecs: 270, isPredicted: false },
      { time: "-02h", level_m: 4.6, discharge_cumecs: 410, isPredicted: false },
      { time: "NOW",  level_m: 5.4, discharge_cumecs: 620, isPredicted: false },
      { time: "+02h", level_m: 7.3, discharge_cumecs: 1250, isPredicted: true },
      { time: "+04h", level_m: 8.1, discharge_cumecs: 1600, isPredicted: true },
      { time: "+06h", level_m: 6.5, discharge_cumecs: 910, isPredicted: true },
      { time: "+08h", level_m: 4.8, discharge_cumecs: 490, isPredicted: true },
    ],
    preventiveDirectives: [
      {
        id: "dir-301",
        category: "HIGHWAY",
        title: "Preemptive Toe-Slope Scour Warning",
        action: "Order emergency sandbagging at Marwari bridge abutments to prevent river scour undercutting the slope.",
        priority: "IMMEDIATE",
        deadline: "T - 60 mins",
        executed: false,
      },
    ],
    infrastructure: [
      {
        id: "infra-6",
        name: "Marwari Alaknanda Bridge",
        type: "BRIDGE",
        coords: [30.5591, 79.5682],
        riskLevel: "HIGH",
        bufferDistanceM: 25,
      },
    ],
  },
  {
    id: "uttarkashi_01",
    name: "Uttarkashi (Bhagirathi Gorge Basin)",
    district: "Uttarkashi",
    center: [30.7268, 78.4354],
    currentRisk: 42.0,
    alertColor: "YELLOW",
    primaryTrigger: "Moderate Runoff Advisory (Watch Status)",
    leadTimeMinutes: 375,
    dangerMarkM: 8.0,
    warningMarkM: 6.5,
    telemetry: {
      rainfall_mm: 22.0,
      soil_moisture_pct: 65.0,
      slope_deg: 29.5,
      river_level_m: 3.1,
      seismic_mag: 0.8,
    },
    hydrograph: [
      { time: "-06h", level_m: 2.1, discharge_cumecs: 110, isPredicted: false },
      { time: "-04h", level_m: 2.4, discharge_cumecs: 140, isPredicted: false },
      { time: "-02h", level_m: 2.8, discharge_cumecs: 180, isPredicted: false },
      { time: "NOW",  level_m: 3.1, discharge_cumecs: 210, isPredicted: false },
      { time: "+02h", level_m: 4.2, discharge_cumecs: 380, isPredicted: true },
      { time: "+04h", level_m: 5.6, discharge_cumecs: 610, isPredicted: true },
      { time: "+06h", level_m: 5.1, discharge_cumecs: 520, isPredicted: true },
      { time: "+08h", level_m: 4.0, discharge_cumecs: 330, isPredicted: true },
    ],
    preventiveDirectives: [
      {
        id: "dir-401",
        category: "DAM",
        title: "Maneri Bhali Barrage Gate Inspection",
        action: "Confirm readiness of automatic crest gates in case upstream tributaries experience cloudburst spikes.",
        priority: "STANDBY",
        deadline: "T - 180 mins",
        executed: true,
      },
    ],
    infrastructure: [
      {
        id: "infra-7",
        name: "Maneri Bhali Stage I Dam",
        type: "DAM",
        coords: [30.7389, 78.4621],
        riskLevel: "MODERATE",
        bufferDistanceM: 100,
      },
    ],
  },
  {
    id: "rishikesh_01",
    name: "Rishikesh Plains (Ganga Confluence)",
    district: "Dehradun",
    center: [30.0869, 78.2676],
    currentRisk: 24.5,
    alertColor: "GREEN",
    primaryTrigger: "Normal Flow (Downstream Flood Wave Buffer Zone)",
    leadTimeMinutes: 870,
    dangerMarkM: 340.5,
    warningMarkM: 339.5,
    telemetry: {
      rainfall_mm: 8.0,
      soil_moisture_pct: 45.0,
      slope_deg: 8.0,
      river_level_m: 337.8,
      seismic_mag: 0.2,
    },
    hydrograph: [
      { time: "-06h", level_m: 337.2, discharge_cumecs: 420, isPredicted: false },
      { time: "-04h", level_m: 337.4, discharge_cumecs: 450, isPredicted: false },
      { time: "-02h", level_m: 337.6, discharge_cumecs: 480, isPredicted: false },
      { time: "NOW",  level_m: 337.8, discharge_cumecs: 510, isPredicted: false },
      { time: "+02h", level_m: 338.1, discharge_cumecs: 590, isPredicted: true },
      { time: "+04h", level_m: 338.5, discharge_cumecs: 720, isPredicted: true },
      { time: "+06h", level_m: 339.1, discharge_cumecs: 880, isPredicted: true },
      { time: "+08h", level_m: 339.4, discharge_cumecs: 960, isPredicted: true },
    ],
    preventiveDirectives: [
      {
        id: "dir-501",
        category: "PILGRIMAGE",
        title: "Ganga Ghats Rafting & Bathing Advisory",
        action: "Routine advisory: Restrict river rafting operations if upstream surge passes Devprayag gauge.",
        priority: "STANDBY",
        deadline: "T - 360 mins",
        executed: true,
      },
    ],
    infrastructure: [
      {
        id: "infra-8",
        name: "Ram Jhula Suspension Bridge",
        type: "BRIDGE",
        coords: [30.1235, 78.3182],
        riskLevel: "SAFE",
        bufferDistanceM: 80,
      },
    ],
  },
];

export const INITIAL_MOCK_SOS_EVENTS: SOSEvent[] = [
  {
    id: "sos-101",
    device_uuid: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
    lat: 30.5582,
    lng: 79.5651,
    status: "SOS",
    sos_type: "TRAPPED IN RIVER VALLEY",
    is_mesh_relayed: true,
    created_at: new Date(Date.now() - 4 * 60000).toISOString(),
  },
  {
    id: "sos-102",
    device_uuid: "550e8400-e29b-41d4-a716-446655440001",
    lat: 30.5565,
    lng: 79.5638,
    status: "SOS",
    sos_type: "BRIDGE APPROACH WASHED OUT",
    is_mesh_relayed: true,
    created_at: new Date(Date.now() - 9 * 60000).toISOString(),
  },
  {
    id: "sos-105",
    device_uuid: "550e8400-e29b-41d4-a716-446655440004",
    lat: 30.5532,
    lng: 79.5615,
    status: "SAFE",
    sos_type: "EVACUATED TO JOSHIMATH HELIPAD SHELTER",
    is_mesh_relayed: false,
    created_at: new Date(Date.now() - 28 * 60000).toISOString(),
  },
];

export const INITIAL_MOCK_CLUSTERS: SOSCluster[] = [
  {
    cluster_id: 1,
    center_lat: 30.5578,
    center_lng: 79.5645,
    total_people: 47,
    priority: "P1",
    dispatched: false,
  },
  {
    cluster_id: 2,
    center_lat: 30.5552,
    center_lng: 79.5671,
    total_people: 22,
    priority: "P1",
    dispatched: false,
  },
];