import {
  HazardZone,
  SOSCluster,
  SOSEvent,
  CitizenLocation,
  DisasterEpicenter,
  RegionalAlert,
} from "./types";

// Alias for backward compat
export const HIMALAYAN_ZONES: HazardZone[] = [];

// All-India Flood Monitoring Zones — SIH 2026 PS: SIH26192
export const INDIA_FLOOD_ZONES: HazardZone[] = [
  {
    id: "chamoli_01",
    name: "Chamoli (Rishi Ganga - Dhauliganga Valley)",
    district: "Chamoli",
    center: [30.5573, 79.5642],
    currentRisk: 86.4,
    alertColor: "RED",
    primaryTrigger: "Cryo-Seismic GLOF Signature (4.6M Tremor + Moraine Lake Breached)",
    leadTimeMinutes: 225, // 3h 45m
    dangerMarkM: 7.5,
    warningMarkM: 6.0,
    telemetry: {
      rainfall_mm: 18.5,
      soil_moisture_pct: 82.0,
      slope_deg: 44.5,
      river_level_m: 6.8,
      seismic_mag: 4.6,
    },
    hydrograph: [
      { time: "-06h", level_m: 3.2, discharge_cumecs: 180, isPredicted: false },
      { time: "-04h", level_m: 3.6, discharge_cumecs: 240, isPredicted: false },
      { time: "-02h", level_m: 4.8, discharge_cumecs: 460, isPredicted: false },
      { time: "NOW",  level_m: 6.8, discharge_cumecs: 890, isPredicted: false },
      { time: "+02h", level_m: 7.9, discharge_cumecs: 1420, isPredicted: true },
      { time: "+04h", level_m: 8.6, discharge_cumecs: 1850, isPredicted: true },
      { time: "+06h", level_m: 7.2, discharge_cumecs: 1100, isPredicted: true },
      { time: "+08h", level_m: 5.4, discharge_cumecs: 680, isPredicted: true },
    ],
    preventiveDirectives: [
      {
        id: "dir-101",
        category: "DAM",
        title: "Tapovan-Vishnugad Barrage Sluice Pre-Release",
        action: "Open Spillway Gates 1, 2, and 4 by 45% to lower reservoir baseline by 3.5m ahead of incoming 1,850 m³/s surge.",
        priority: "IMMEDIATE",
        deadline: "T - 90 mins",
        executed: false,
      },
      {
        id: "dir-102",
        category: "HIGHWAY",
        title: "NH-7 (Badrinath Highway) Traffic Halt",
        action: "Order Uttarakhand Police & BRO to halt civilian traffic at Helang and Joshimath checkpoints. Close low-lying river bridges.",
        priority: "IMMEDIATE",
        deadline: "T - 45 mins",
        executed: false,
      },
      {
        id: "dir-103",
        category: "PILGRIMAGE",
        title: "Govindghat Riverside Pilgrimage Camp Clearing",
        action: "Order SDMA SDRF personnel to evacuate 400+ pilgrims from temporary riverbank shelters to high-ground Gurdwara grounds.",
        priority: "IMMEDIATE",
        deadline: "T - 60 mins",
        executed: false,
      },
      {
        id: "dir-104",
        category: "POWER",
        title: "NTPC Hydroelectric Intake Tunnel Shutdown",
        action: "Depressurize power intake tunnels to avoid silt sedimentation and structural collapse.",
        priority: "ADVISORY",
        deadline: "T - 120 mins",
        executed: true,
      },
    ],
    infrastructure: [
      {
        id: "infra-1",
        name: "Tapovan Vishnugad Barrage",
        type: "BARRAGE",
        coords: [30.5489, 79.5785],
        riskLevel: "HIGH",
        bufferDistanceM: 30,
      },
      {
        id: "infra-2",
        name: "Rishi Ganga Hydel Intake Bridge",
        type: "BRIDGE",
        coords: [30.5542, 79.5698],
        riskLevel: "HIGH",
        bufferDistanceM: 15,
      },
      {
        id: "infra-3",
        name: "Joshimath Helipad Base (High Ground)",
        type: "SHELTER",
        coords: [30.5621, 79.5523],
        riskLevel: "SAFE",
        bufferDistanceM: 450,
      },
    ],
    epicenter: {
      id: "epi-chamoli-01",
      zone_id: "chamoli_01",
      name: "Raunthi Glacier Moraine Lake Breach (GLOF Origin)",
      type: "GLOF_MORAINE_BREACH",
      coords: [30.5724, 79.5812],
      elevation_m: 5420,
      estimated_volume_m3: "1.85M m³",
      detection_source: "Cryo-Seismic Tremor (4.6M) + INSAT-3DR Thermal Anomaly",
      surge_path: [
        [30.5724, 79.5812],
        [30.5645, 79.5742],
        [30.5582, 79.5651],
        [30.5489, 79.5785],
        [30.5420, 79.5490],
        [30.5310, 79.5380],
      ],
      checkpoints: [
        { name: "Raini Bridge Confluence", distance_km: 4.2, eta_minutes: 18, peak_surge_m: 8.6 },
        { name: "Tapovan-Vishnugad Barrage", distance_km: 7.8, eta_minutes: 42, peak_surge_m: 7.9 },
        { name: "Joshimath Helipad Lowlands", distance_km: 14.5, eta_minutes: 75, peak_surge_m: 6.4 },
        { name: "Helang NH-7 River Crossing", distance_km: 21.0, eta_minutes: 110, peak_surge_m: 5.1 },
      ],
    },
  },
  {
    id: "kedarnath_01",
    name: "Kedarnath Valley (Mandakini Catchment)",
    district: "Rudraprayag",
    center: [30.7346, 79.0669],
    currentRisk: 64.2,
    alertColor: "ORANGE",
    primaryTrigger: "High Saturated Runoff & Localized Cloudburst Warning",
    leadTimeMinutes: 85,
    dangerMarkM: 6.8,
    warningMarkM: 5.5,
    telemetry: {
      rainfall_mm: 68.2,
      soil_moisture_pct: 91.5,
      slope_deg: 38.0,
      river_level_m: 4.9,
      seismic_mag: 1.2,
    },
    hydrograph: [
      { time: "-06h", level_m: 2.8, discharge_cumecs: 120, isPredicted: false },
      { time: "-04h", level_m: 3.2, discharge_cumecs: 160, isPredicted: false },
      { time: "-02h", level_m: 4.1, discharge_cumecs: 290, isPredicted: false },
      { time: "NOW",  level_m: 4.9, discharge_cumecs: 480, isPredicted: false },
      { time: "+02h", level_m: 6.9, discharge_cumecs: 980, isPredicted: true },
      { time: "+04h", level_m: 7.4, discharge_cumecs: 1120, isPredicted: true },
      { time: "+06h", level_m: 5.8, discharge_cumecs: 620, isPredicted: true },
      { time: "+08h", level_m: 4.2, discharge_cumecs: 340, isPredicted: true },
    ],
    preventiveDirectives: [
      {
        id: "dir-201",
        category: "PILGRIMAGE",
        title: "Gaurikund-Kedarnath Trek Trail Suspension",
        action: "Halt uphill pilgrim movement at Gaurikund base. Direct downhill walkers to designated concrete shelters.",
        priority: "IMMEDIATE",
        deadline: "T - 30 mins",
        executed: false,
      },
      {
        id: "dir-202",
        category: "DAM",
        title: "Singoli-Bhatwari Hydroelectric Gate Flush",
        action: "Initiate radial gate opening to flush sediment and prevent reservoir backwater surge.",
        priority: "ADVISORY",
        deadline: "T - 75 mins",
        executed: false,
      },
    ],
    infrastructure: [
      {
        id: "infra-4",
        name: "Rambara Suspension Footbridge",
        type: "BRIDGE",
        coords: [30.7012, 79.0534],
        riskLevel: "HIGH",
        bufferDistanceM: 20,
      },
      {
        id: "infra-5",
        name: "Gaurikund Evacuation Muster Station",
        type: "SHELTER",
        coords: [30.6521, 79.0278],
        riskLevel: "SAFE",
        bufferDistanceM: 220,
      },
    ],
  },
  {
    id: "joshimath_01",
    name: "Joshimath Subsidence & Alaknanda Buffer",
    district: "Chamoli",
    center: [30.5562, 79.5663],
    currentRisk: 78.9,
    alertColor: "RED",
    primaryTrigger: "Geotechnical Slope Saturation & Toe-Erosion Breach Risk",
    leadTimeMinutes: 170,
    dangerMarkM: 7.2,
    warningMarkM: 5.8,
    telemetry: {
      rainfall_mm: 34.0,
      soil_moisture_pct: 87.2,
      slope_deg: 41.2,
      river_level_m: 5.4,
      seismic_mag: 3.1,
    },
    hydrograph: [
      { time: "-06h", level_m: 3.0, discharge_cumecs: 190, isPredicted: false },
      { time: "-04h", level_m: 3.8, discharge_cumecs: 270, isPredicted: false },
      { time: "-02h", level_m: 4.6, discharge_cumecs: 410, isPredicted: false },
      { time: "NOW",  level_m: 5.4, discharge_cumecs: 620, isPredicted: false },
      { time: "+02h", level_m: 7.3, discharge_cumecs: 1250, isPredicted: true },
      { time: "+04h", level_m: 8.1, discharge_cumecs: 1600, isPredicted: true },
      { time: "+06h", level_m: 6.5, discharge_cumecs: 910, isPredicted: true },
      { time: "+08h", level_m: 4.8, discharge_cumecs: 490, isPredicted: true },
    ],
    preventiveDirectives: [
      {
        id: "dir-301",
        category: "HIGHWAY",
        title: "Preemptive Toe-Slope Scour Warning",
        action: "Order emergency sandbagging at Marwari bridge abutments to prevent river scour undercutting the slope.",
        priority: "IMMEDIATE",
        deadline: "T - 60 mins",
        executed: false,
      },
    ],
    infrastructure: [
      {
        id: "infra-6",
        name: "Marwari Alaknanda Bridge",
        type: "BRIDGE",
        coords: [30.5591, 79.5682],
        riskLevel: "HIGH",
        bufferDistanceM: 25,
      },
    ],
  },
  {
    id: "uttarkashi_01",
    name: "Uttarkashi (Bhagirathi Gorge Basin)",
    district: "Uttarkashi",
    center: [30.7268, 78.4354],
    currentRisk: 42.0,
    alertColor: "YELLOW",
    primaryTrigger: "Moderate Runoff Advisory (Watch Status)",
    leadTimeMinutes: 375,
    dangerMarkM: 8.0,
    warningMarkM: 6.5,
    telemetry: {
      rainfall_mm: 22.0,
      soil_moisture_pct: 65.0,
      slope_deg: 29.5,
      river_level_m: 3.1,
      seismic_mag: 0.8,
    },
    hydrograph: [
      { time: "-06h", level_m: 2.1, discharge_cumecs: 110, isPredicted: false },
      { time: "-04h", level_m: 2.4, discharge_cumecs: 140, isPredicted: false },
      { time: "-02h", level_m: 2.8, discharge_cumecs: 180, isPredicted: false },
      { time: "NOW",  level_m: 3.1, discharge_cumecs: 210, isPredicted: false },
      { time: "+02h", level_m: 4.2, discharge_cumecs: 380, isPredicted: true },
      { time: "+04h", level_m: 5.6, discharge_cumecs: 610, isPredicted: true },
      { time: "+06h", level_m: 5.1, discharge_cumecs: 520, isPredicted: true },
      { time: "+08h", level_m: 4.0, discharge_cumecs: 330, isPredicted: true },
    ],
    preventiveDirectives: [
      {
        id: "dir-401",
        category: "DAM",
        title: "Maneri Bhali Barrage Gate Inspection",
        action: "Confirm readiness of automatic crest gates in case upstream tributaries experience cloudburst spikes.",
        priority: "STANDBY",
        deadline: "T - 180 mins",
        executed: true,
      },
    ],
    infrastructure: [
      {
        id: "infra-7",
        name: "Maneri Bhali Stage I Dam",
        type: "DAM",
        coords: [30.7389, 78.4621],
        riskLevel: "MODERATE",
        bufferDistanceM: 100,
      },
    ],
  },
  {
    id: "rishikesh_01",
    name: "Rishikesh Plains (Ganga Confluence)",
    district: "Dehradun",
    center: [30.0869, 78.2676],
    currentRisk: 24.5,
    alertColor: "GREEN",
    primaryTrigger: "Normal Flow (Downstream Flood Wave Buffer Zone)",
    leadTimeMinutes: 870,
    dangerMarkM: 340.5,
    warningMarkM: 339.5,
    telemetry: {
      rainfall_mm: 8.0,
      soil_moisture_pct: 45.0,
      slope_deg: 8.0,
      river_level_m: 337.8,
      seismic_mag: 0.2,
    },
    hydrograph: [
      { time: "-06h", level_m: 337.2, discharge_cumecs: 420, isPredicted: false },
      { time: "-04h", level_m: 337.4, discharge_cumecs: 450, isPredicted: false },
      { time: "-02h", level_m: 337.6, discharge_cumecs: 480, isPredicted: false },
      { time: "NOW",  level_m: 337.8, discharge_cumecs: 510, isPredicted: false },
      { time: "+02h", level_m: 338.1, discharge_cumecs: 590, isPredicted: true },
      { time: "+04h", level_m: 338.5, discharge_cumecs: 720, isPredicted: true },
      { time: "+06h", level_m: 339.1, discharge_cumecs: 880, isPredicted: true },
      { time: "+08h", level_m: 339.4, discharge_cumecs: 960, isPredicted: true },
    ],
    preventiveDirectives: [
      {
        id: "dir-501",
        category: "PILGRIMAGE",
        title: "Ganga Ghats Rafting & Bathing Advisory",
        action: "Routine advisory: Restrict river rafting operations if upstream surge passes Devprayag gauge.",
        priority: "STANDBY",
        deadline: "T - 360 mins",
        executed: true,
      },
    ],
    infrastructure: [
      {
        id: "infra-8",
        name: "Ram Jhula Suspension Bridge",
        type: "BRIDGE",
        coords: [30.1235, 78.3182],
        riskLevel: "SAFE",
        bufferDistanceM: 80,
      },
    ],
  },
  // ─── ASSAM / BRAHMAPUTRA ──────────────────────────────────────────────
  {
    id: "assam_brahmaputra_01",
    name: "Brahmaputra Floodplain (Majuli Island)",
    district: "Jorhat / Majuli, Assam",
    center: [26.9500, 94.2200],
    currentRisk: 71.3,
    alertColor: "ORANGE" as const,
    primaryTrigger: "Brahmaputra Embankment Breach — Monsoon Peak Discharge 61,000 cumecs",
    leadTimeMinutes: 120,
    dangerMarkM: 89.0,
    warningMarkM: 87.5,
    telemetry: { rainfall_mm: 92.0, soil_moisture_pct: 94.0, slope_deg: 4.5, river_level_m: 87.8, seismic_mag: 0.3 },
    hydrograph: [
      { time: "-06h", level_m: 85.2, discharge_cumecs: 42000, isPredicted: false },
      { time: "-04h", level_m: 86.1, discharge_cumecs: 48000, isPredicted: false },
      { time: "-02h", level_m: 86.9, discharge_cumecs: 53000, isPredicted: false },
      { time: "NOW",  level_m: 87.8, discharge_cumecs: 61000, isPredicted: false },
      { time: "+02h", level_m: 88.6, discharge_cumecs: 71000, isPredicted: true },
      { time: "+04h", level_m: 89.3, discharge_cumecs: 78000, isPredicted: true },
      { time: "+06h", level_m: 88.1, discharge_cumecs: 65000, isPredicted: true },
      { time: "+08h", level_m: 86.4, discharge_cumecs: 52000, isPredicted: true },
    ],
    preventiveDirectives: [
      { id: "dir-601", category: "HIGHWAY", title: "NH-27 Floodplain Bypass Activation", action: "Alert NHAI to activate Kaziranga bypass. Suspend NH-27 through Majuli floodplain.", priority: "IMMEDIATE", deadline: "T - 90 mins", executed: false },
    ],
    infrastructure: [{ id: "infra-a1", name: "Majuli Ferry Ghat Evacuation Point", type: "SHELTER", coords: [26.9488, 94.1932], riskLevel: "HIGH", bufferDistanceM: 30 }],
  },
  // ─── KERALA / WESTERN GHATS ─────────────────────────────────────────
  {
    id: "kerala_chalakudy_01",
    name: "Chalakudy River (Western Ghats Runoff)",
    district: "Thrissur, Kerala",
    center: [10.3010, 76.3316],
    currentRisk: 58.7,
    alertColor: "ORANGE" as const,
    primaryTrigger: "Orographic Rainfall 148mm — Poringalkuthu Reservoir Overflow Risk",
    leadTimeMinutes: 95,
    dangerMarkM: 12.5,
    warningMarkM: 10.0,
    telemetry: { rainfall_mm: 148.0, soil_moisture_pct: 97.0, slope_deg: 28.0, river_level_m: 9.8, seismic_mag: 0.1 },
    hydrograph: [
      { time: "-06h", level_m: 7.2, discharge_cumecs: 800, isPredicted: false },
      { time: "-04h", level_m: 8.1, discharge_cumecs: 1200, isPredicted: false },
      { time: "-02h", level_m: 9.1, discharge_cumecs: 1800, isPredicted: false },
      { time: "NOW",  level_m: 9.8, discharge_cumecs: 2400, isPredicted: false },
      { time: "+02h", level_m: 11.4, discharge_cumecs: 3600, isPredicted: true },
      { time: "+04h", level_m: 13.1, discharge_cumecs: 4800, isPredicted: true },
      { time: "+06h", level_m: 11.8, discharge_cumecs: 3900, isPredicted: true },
      { time: "+08h", level_m: 10.2, discharge_cumecs: 2800, isPredicted: true },
    ],
    preventiveDirectives: [
      { id: "dir-701", category: "DAM", title: "Poringalkuthu Dam Controlled Release", action: "Open 4 of 6 sluice gates at 60% to prevent uncontrolled overflow into Chalakudy town.", priority: "IMMEDIATE", deadline: "T - 45 mins", executed: false },
    ],
    infrastructure: [{ id: "infra-b1", name: "Chalakudy Town Riverside Shelter", type: "SHELTER", coords: [10.2998, 76.3289], riskLevel: "HIGH", bufferDistanceM: 20 }],
  },
  // ─── BIHAR / KOSI PLAINS ────────────────────────────────────────────
  {
    id: "bihar_kosi_01",
    name: "Kosi River Embankment (Supaul Zone)",
    district: "Supaul, Bihar",
    center: [25.8921, 86.5973],
    currentRisk: 47.2,
    alertColor: "YELLOW" as const,
    primaryTrigger: "Kosi Embankment Seepage — Nepal Birpur Barrage Spill Release",
    leadTimeMinutes: 300,
    dangerMarkM: 33.5,
    warningMarkM: 32.0,
    telemetry: { rainfall_mm: 55.0, soil_moisture_pct: 88.0, slope_deg: 1.8, river_level_m: 31.8, seismic_mag: 0.2 },
    hydrograph: [
      { time: "-06h", level_m: 30.1, discharge_cumecs: 18000, isPredicted: false },
      { time: "-04h", level_m: 30.8, discharge_cumecs: 21000, isPredicted: false },
      { time: "-02h", level_m: 31.4, discharge_cumecs: 24000, isPredicted: false },
      { time: "NOW",  level_m: 31.8, discharge_cumecs: 27000, isPredicted: false },
      { time: "+02h", level_m: 32.5, discharge_cumecs: 32000, isPredicted: true },
      { time: "+04h", level_m: 33.8, discharge_cumecs: 39000, isPredicted: true },
      { time: "+06h", level_m: 32.9, discharge_cumecs: 34000, isPredicted: true },
      { time: "+08h", level_m: 31.6, discharge_cumecs: 26000, isPredicted: true },
    ],
    preventiveDirectives: [
      { id: "dir-801", category: "HIGHWAY", title: "NH-107 Embankment Load Advisory", action: "Deploy Bihar Police to restrict heavy trucks on embankment roads to prevent overload failure.", priority: "ADVISORY", deadline: "T - 180 mins", executed: false },
    ],
    infrastructure: [{ id: "infra-c1", name: "Kosi Western Embankment (KWE)", type: "BARRAGE", coords: [25.9012, 86.5821], riskLevel: "MODERATE", bufferDistanceM: 200 }],
  },
  // ─── ODISHA / MAHANADI DELTA ────────────────────────────────────────
  {
    id: "odisha_mahanadi_01",
    name: "Mahanadi Delta (Cuttack Floodplain)",
    district: "Cuttack, Odisha",
    center: [20.4625, 85.8828],
    currentRisk: 34.5,
    alertColor: "YELLOW" as const,
    primaryTrigger: "Hirakud Reservoir Spillway — Coastal Inundation Watch",
    leadTimeMinutes: 480,
    dangerMarkM: 15.0,
    warningMarkM: 13.5,
    telemetry: { rainfall_mm: 38.0, soil_moisture_pct: 76.0, slope_deg: 2.2, river_level_m: 12.8, seismic_mag: 0.1 },
    hydrograph: [
      { time: "-06h", level_m: 11.2, discharge_cumecs: 12000, isPredicted: false },
      { time: "-04h", level_m: 11.8, discharge_cumecs: 14000, isPredicted: false },
      { time: "-02h", level_m: 12.4, discharge_cumecs: 17000, isPredicted: false },
      { time: "NOW",  level_m: 12.8, discharge_cumecs: 19000, isPredicted: false },
      { time: "+02h", level_m: 13.6, discharge_cumecs: 24000, isPredicted: true },
      { time: "+04h", level_m: 14.2, discharge_cumecs: 28000, isPredicted: true },
      { time: "+06h", level_m: 13.8, discharge_cumecs: 25000, isPredicted: true },
      { time: "+08h", level_m: 12.9, discharge_cumecs: 20000, isPredicted: true },
    ],
    preventiveDirectives: [
      { id: "dir-901", category: "PILGRIMAGE", title: "Puri Coastal Evacuation Advisory", action: "Issue evacuation notice for coastal villages within 5km. Coordinate with Odisha SDRF.", priority: "STANDBY", deadline: "T - 300 mins", executed: true },
    ],
    infrastructure: [{ id: "infra-d1", name: "Cuttack River Wall", type: "BARRAGE", coords: [20.4525, 85.8923], riskLevel: "SAFE", bufferDistanceM: 150 }],
  },

  // ─── HIMACHAL PRADESH / BEAS BASIN ──────────────────────────────────────
  {
    id: "himachal_kullu_01",
    name: "Parvati & Beas Valley (Kullu - Manikaran)",
    district: "Kullu, Himachal Pradesh",
    center: [31.9578, 77.1095],
    currentRisk: 88.2,
    alertColor: "RED" as const,
    primaryTrigger: "Cloudburst Inundation & Debris Torrent — Beas River Surge",
    leadTimeMinutes: 110,
    dangerMarkM: 8.0,
    warningMarkM: 6.8,
    telemetry: { rainfall_mm: 72.4, soil_moisture_pct: 94.5, slope_deg: 46.0, river_level_m: 7.7, seismic_mag: 1.8 },
    hydrograph: [
      { time: "-06h", level_m: 3.4, discharge_cumecs: 190, isPredicted: false },
      { time: "-04h", level_m: 4.1, discharge_cumecs: 310, isPredicted: false },
      { time: "-02h", level_m: 5.6, discharge_cumecs: 680, isPredicted: false },
      { time: "NOW",  level_m: 7.7, discharge_cumecs: 1240, isPredicted: false },
      { time: "+02h", level_m: 8.8, discharge_cumecs: 1920, isPredicted: true },
      { time: "+04h", level_m: 8.2, discharge_cumecs: 1550, isPredicted: true },
      { time: "+06h", level_m: 6.5, discharge_cumecs: 980, isPredicted: true },
      { time: "+08h", level_m: 5.1, discharge_cumecs: 520, isPredicted: true },
    ],
    preventiveDirectives: [
      { id: "dir-hp-01", category: "HIGHWAY", title: "Kullu-Manali NH-3 Traffic Suspension", action: "Halt all vehicle movement along vulnerable riverside road stretches. Move travelers uphill.", priority: "IMMEDIATE", deadline: "T - 30 mins", executed: false },
    ],
    infrastructure: [{ id: "infra-hp1", name: "Pandoh Dam Sluice", type: "DAM", coords: [31.6708, 77.0700], riskLevel: "HIGH", bufferDistanceM: 200 }],
  },

  // ─── JAMMU & KASHMIR / JHELUM BASIN ────────────────────────────────────
  {
    id: "jk_jhelum_01",
    name: "Jhelum Floodplain (Srinagar - Sangam)",
    district: "Srinagar / Anantnag, J&K",
    center: [34.0837, 74.7973],
    currentRisk: 64.5,
    alertColor: "ORANGE" as const,
    primaryTrigger: "Snowmelt Runoff + Continuous Downpour (Ram Munshi Bagh Stage Rising)",
    leadTimeMinutes: 280,
    dangerMarkM: 21.0,
    warningMarkM: 18.0,
    telemetry: { rainfall_mm: 44.0, soil_moisture_pct: 88.0, slope_deg: 5.5, river_level_m: 19.4, seismic_mag: 0.5 },
    hydrograph: [
      { time: "-06h", level_m: 14.5, discharge_cumecs: 1500, isPredicted: false },
      { time: "-04h", level_m: 16.2, discharge_cumecs: 2100, isPredicted: false },
      { time: "-02h", level_m: 18.1, discharge_cumecs: 2800, isPredicted: false },
      { time: "NOW",  level_m: 19.4, discharge_cumecs: 3400, isPredicted: false },
      { time: "+02h", level_m: 20.6, discharge_cumecs: 4100, isPredicted: true },
      { time: "+04h", level_m: 21.3, discharge_cumecs: 4600, isPredicted: true },
      { time: "+06h", level_m: 20.1, discharge_cumecs: 3900, isPredicted: true },
      { time: "+08h", level_m: 18.5, discharge_cumecs: 3000, isPredicted: true },
    ],
    preventiveDirectives: [
      { id: "dir-jk-01", category: "DAM", title: "Flood Spill Channel Diversion Activation", action: "Open Padshahi Bagh flood spill gates to bypass Srinagar city center.", priority: "IMMEDIATE", deadline: "T - 60 mins", executed: false },
    ],
    infrastructure: [{ id: "infra-jk1", name: "Sangam Hydrometric Gauge", type: "BRIDGE", coords: [33.8200, 75.0800], riskLevel: "MODERATE", bufferDistanceM: 100 }],
  },

  // ─── WEST BENGAL & SIKKIM / TEESTA BASIN ────────────────────────────────
  {
    id: "wb_teesta_01",
    name: "Teesta River Corridor (Jalpaiguri - Sevoke)",
    district: "Jalpaiguri, West Bengal",
    center: [26.5400, 88.7200],
    currentRisk: 91.0,
    alertColor: "RED" as const,
    primaryTrigger: "Upstream Chungthang Dam Outburst Surge Wave Transmission",
    leadTimeMinutes: 140,
    dangerMarkM: 52.5,
    warningMarkM: 50.0,
    telemetry: { rainfall_mm: 58.0, soil_moisture_pct: 91.0, slope_deg: 28.0, river_level_m: 51.8, seismic_mag: 3.8 },
    hydrograph: [
      { time: "-06h", level_m: 44.0, discharge_cumecs: 3200, isPredicted: false },
      { time: "-04h", level_m: 46.5, discharge_cumecs: 4800, isPredicted: false },
      { time: "-02h", level_m: 49.2, discharge_cumecs: 7100, isPredicted: false },
      { time: "NOW",  level_m: 51.8, discharge_cumecs: 9500, isPredicted: false },
      { time: "+02h", level_m: 53.4, discharge_cumecs: 12800, isPredicted: true },
      { time: "+04h", level_m: 52.8, discharge_cumecs: 11200, isPredicted: true },
      { time: "+06h", level_m: 49.5, discharge_cumecs: 7500, isPredicted: true },
      { time: "+08h", level_m: 46.0, discharge_cumecs: 4600, isPredicted: true },
    ],
    preventiveDirectives: [
      { id: "dir-wb-01", category: "HIGHWAY", title: "Coronation Bridge & NH-10 Closure", action: "Shut Kalimpong-Sikkim corridor. Evacuate low-lying riverbank villages downstream.", priority: "IMMEDIATE", deadline: "T - 40 mins", executed: false },
    ],
    infrastructure: [{ id: "infra-wb1", name: "Teesta Barrage (Gajoldoba)", type: "BARRAGE", coords: [26.7533, 88.5833], riskLevel: "HIGH", bufferDistanceM: 300 }],
  },
];


// Backward-compat alias — points to Uttarakhand/HP zones (first 5)
HIMALAYAN_ZONES.push(...INDIA_FLOOD_ZONES.slice(0, 5));

export const INITIAL_MOCK_SOS_EVENTS: SOSEvent[] = [
  {
    id: "sos-101",
    device_uuid: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
    lat: 30.5582,
    lng: 79.5651,
    status: "SOS",
    sos_type: "TRAPPED IN RIVER VALLEY",
    is_mesh_relayed: true,
    created_at: new Date(Date.now() - 4 * 60000).toISOString(),
  },
  {
    id: "sos-102",
    device_uuid: "550e8400-e29b-41d4-a716-446655440001",
    lat: 30.5565,
    lng: 79.5638,
    status: "SOS",
    sos_type: "BRIDGE APPROACH WASHED OUT",
    is_mesh_relayed: true,
    created_at: new Date(Date.now() - 9 * 60000).toISOString(),
  },
  {
    id: "sos-105",
    device_uuid: "550e8400-e29b-41d4-a716-446655440004",
    lat: 30.5532,
    lng: 79.5615,
    status: "SAFE",
    sos_type: "EVACUATED TO JOSHIMATH HELIPAD SHELTER",
    is_mesh_relayed: false,
    created_at: new Date(Date.now() - 28 * 60000).toISOString(),
  },
];

export const INITIAL_MOCK_CLUSTERS: SOSCluster[] = [
  {
    cluster_id: 1,
    center_lat: 30.5578,
    center_lng: 79.5645,
    total_people: 47,
    priority: "P1",
    dispatched: false,
  },
  {
    cluster_id: 2,
    center_lat: 30.5552,
    center_lng: 79.5671,
    total_people: 22,
    priority: "P1",
    dispatched: false,
  },
];

export const INITIAL_CITIZEN_LOCATIONS: CitizenLocation[] = [
  {
    id: "cit-101",
    device_uuid: "node-f81d4f-live",
    lat: 30.5582,
    lng: 79.5651,
    is_live: true,
    last_seen_minutes_ago: 1,
    accuracy_radius_m: 14,
    drift_radius_m: 0,
    battery_pct: 78,
    status: "SOS",
    sos_type: "TRAPPED IN RIVER VALLEY (RAPID RISE)",
    mesh_hops: 0,
    breadcrumbs: [
      [30.5575, 79.5640],
      [30.5582, 79.5651],
    ],
  },
  {
    id: "cit-102",
    device_uuid: "node-550e84-mesh",
    lat: 30.5565,
    lng: 79.5638,
    is_live: false,
    last_seen_minutes_ago: 18,
    accuracy_radius_m: 65,
    drift_radius_m: 350,
    battery_pct: 34,
    status: "SOS",
    sos_type: "LAST SEEN NEAR WASHED BRIDGE PIER",
    mesh_hops: 2,
    breadcrumbs: [
      [30.5550, 79.5620],
      [30.5565, 79.5638],
    ],
  },
  {
    id: "cit-103",
    device_uuid: "node-a74b12-offline",
    lat: 30.5595,
    lng: 79.5680,
    is_live: false,
    last_seen_minutes_ago: 32,
    accuracy_radius_m: 120,
    drift_radius_m: 600,
    battery_pct: 19,
    status: "SOS",
    sos_type: "COMM CELL TOWER SEVERED (LAST BEACON)",
    mesh_hops: 3,
  },
  {
    id: "cit-104",
    device_uuid: "node-safe-01",
    lat: 30.5532,
    lng: 79.5615,
    is_live: true,
    last_seen_minutes_ago: 0,
    accuracy_radius_m: 8,
    drift_radius_m: 0,
    battery_pct: 92,
    status: "SAFE",
    sos_type: "EVACUATED TO JOSHIMATH HELIPAD SHELTER",
    mesh_hops: 0,
  },
  {
    id: "cit-105",
    device_uuid: "node-volunteer-01",
    lat: 30.5545,
    lng: 79.5628,
    is_live: true,
    last_seen_minutes_ago: 2,
    accuracy_radius_m: 15,
    drift_radius_m: 0,
    battery_pct: 86,
    status: "HELPING",
    sos_type: "CIVIL DEFENSE VOLUNTEER RELAY NODE",
    mesh_hops: 1,
  },
];

export const INITIAL_REGIONAL_ALERTS: RegionalAlert[] = [
  {
    alert_id: "alert-rec-01",
    zone_id: "chamoli_01",
    severity: "CRITICAL RED",
    title: "ZERO-MINUTE MANDATORY EVACUATION DISPATCH",
    message:
      "CRITICAL GLOF / FLASH FLOOD BREACH DETECTED in Rishi Ganga Valley. Evacuate all riverbanks immediately to high ground (>100m vertical elevation).",
    safe_havens: [
      "Joshimath Helipad Multi-Hazard Shelter",
      "Govindghat High Ground Gurdwara",
    ],
    trigger_acoustic_siren: true,
    dispatched_at: new Date(Date.now() - 12 * 60000).toISOString(),
    status: "ACTIVE_IN_EDGE_MESH",
    target_nodes_count: 1420,
    delivery_rate_pct: 98.4,
  },
];